clients:
  - minioClientName: client1
    endpoint: 127.0.0.1:9001
    accessKeyID: minio
    secretAccessKey: minio123
    secure: true
  - minioClientName: client2
    endpoint: 127.0.0.1:9001
    accessKeyID: minio
    secretAccessKey: minio123
    secure: true